### Get all accounts
GET http://localhost:8080/accounts

### get account by nick
GET http://localhost:8080/account/linux_china

###
POST http://localhost:8080/account/update_passwd
Content-Type: application/x-www-form-urlencoded

id=1&password=654321

###